name: CI
on: [push, pull_request] 

jobs:
  test: # needs to be extended
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0
      - name: Initialize OPAM environment
        run: |
          echo "eval $(opam env --shell=sh)" >> $GITHUB_ENV
      - name: Verify OCaml installation
        run: |
          eval $(opam env)
          ocaml -version
          which ocaml
      - name: Build and run checks
        run: mvn verify
