name: CI
on: [push, pull_request] 

jobs:
  test: # needs to be extended
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0
      - name: Install Menhir
        run: |
          eval $(opam env)
          opam install menhir -y
          
      - name: Build and run checks
        run: |
          eval $(opam env)
          export LD_LIBRARY_PATH=$(ocamlc -where):$LD_LIBRARY_PATH
          mvn verify
